name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Fix ng permissions
        working-directory: ./frontend
        run: chmod +x node_modules/.bin/ng

      - name: Build Angular app
        working-directory: ./frontend
        run: node_modules/.bin/ng build --configuration production